export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_NAME_COUNTRIES = "GET_NAME_COUNTRIES";
export const GET_NAME_COUNTRIES_FORM = "GET_NAME_COUNTRIES_FORM";
export const CLEAR_NAME_COUNTRIES_FORM = "CLEAR_NAME_COUNTRIES_FORM";
export const GET_DETAILS = "GET_DETAILS";
